spring:
  profiles:
    active: ${LOGGING_MODE:dev}
  
---

server:
  port: 8083

spring:
  profiles: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://localhost/auth/realms/FAIR4Health
        registration:
          keycloak:
            client-id: test
            client-secret: test
      resourceserver:
        opaquetoken:
          introspection-uri: https://localhost/auth/realms/FAIR4Health/protocol/openid-connect/token/introspect
          client-id: test
          client-secret: test
                  
  cloud:
    gateway:
      default-filters:
      - TokenRelay
      routes:
      - id: oauth_easy_swagger
        uri: ${OAUTH_EASY_URL:http://localhost:8081}
        predicates:
        - Path=/oauth/swagger-ui.html
        filters:
        - StripPrefix=1   
      - id: oauth_easy
        uri: ${OAUTH_EASY_URL:http://localhost:8081}
        predicates:
        - Path=/oauth/**
        filters:
        - StripPrefix=1      
      - id: discovery_swagger
        uri: ${DISCOVERY_URL:http://localhost:8082}
        predicates:
        - Path=/discovery/swagger-ui.html
        filters:
        - StripPrefix=1   
      - id: discovery
        uri: ${DISCOVERY_URL:http://localhost:8082}
        predicates:
        - Path=/discovery/**
        filters:
        - StripPrefix=1      
      - id: ppddm-manager
        uri: ${PPDDM_MANAGER_URL:http://localhost:8181}
        predicates:
        - Path=/ppddm-manager/**
        filters:
        - StripPrefix=1
  